[project]
name = "lactaat"
version = "0.1.0"
description = "Use library lactate-thresholds to calculate threshold and zones"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "lactate-thresholds>=0.3.4",
    "vl-convert-python>=1.7.0",
]
